#PostgreSQL v9.2.1
# gem 'pg', '0.12.2'
common: &common
  adapter: postgresql
  username: russell.schmidt
  password: dirtypussy5!
  host: localhost
  encoding: UTF8

development:
  <<: *common
  database: dev

test:
  <<: *common
  database: test

production:
  <<: *common
  database: production

#
#development:
#  adapter: postgresql
#  database: db/dev
#  username: russell.schmidt
#  password: dirtypussy5!
#  host: localhost
#  encoding: UTF8
#  pool: 5
#  timeout: 5000


#test:
#  adapter: postgresql
#  database: db/dev
#  username: russell.schmidt
#  password: dirtypussy5!
#  host: localhost
#  encoding: UTF8
#  pool: 5
#  timeout: 5000

#production:
#  adapter: postgresql
#  database: db/dev
#  username: russell.schmidt
#  password: dirtypussy5!
#  host: localhost
#  encoding: UTF8
#  pool: 5
#  timeout: 5000
#=end


# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'

#development:
  #adapter: postgresql
  #database: db/test.sqlite3
  #pool: 5
  #timeout: 5000

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.

#test:
  #adapter: postgresql
  #database: db/test.sqlite3
  #pool: 5
  #timeout: 5000

#production:
  #adapter: postgresql
  #database: db/production.sqlite3
  #pool: 5
  #timeout: 5000